{
 "title": "all pods",
 "panels": [
  {
   "title": "Memory Working Set",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum (machine_memory_bytes{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Cpu Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m])) / sum (machine_cpu_cores{instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "singlestat",
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"}) / sum(container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",instance=~\"^$instance$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m]))",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}
{
 "title": "each pod",
 "panels": [
  {
   "title": "Cpu Usage",
   "type": "graph",
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "yaxes": [
    { "format": "Bps", "label": "transmit / receive" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} < in"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}[1m])) by (pod_name)",
     "legendFormat": "{{ pod_name }} > out"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "graph",
   "yaxes": [
    { "format": "bytes", "label": "used" }
   ],
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{image!=\"\",name=~\"^k8s_.*\",instance=~\"^$instance$\",namespace=~\"^$namespace$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}
{
 "title": "Akka.NET Cluster + Phobos 2.x Metrics (Prometheus Data Source)",
 "description": "System-wide Akka.NET metrics used for profiling Akka.NET performance. Gathered via Phobos and OpenTelemetry.",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "role", "label": "Role", "query": "label_values(cluster_role)" },
   { "name": "address", "label": "address", "query": "label_values(akka_address)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Up\"}))",
     "legendFormat": "Up"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"WeaklyUp\"}))",
     "legendFormat": "WeaklyUp"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Joining\"}))",
     "legendFormat": "Joining"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Leaving\"}))",
     "legendFormat": "Leaving"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Exiting\"}))",
     "legendFormat": "Exiting"
    },
    {
     "expr": "ceil(avg(akka_cluster_members_members{status=\"Down\"}))",
     "legendFormat": "Down"
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))"
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "graph",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(avg by(status)(akka_cluster_members_members))",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "ceil(avg(akka_cluster_reachable_members{status=\"False\"}))",
     "legendFormat": "Unreachable"
    }
   ]
  },
  { "title": "Logging and Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Cluster Logging Activity",
   "type": "graph",
   "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(level)(increase(akka_logs_events{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Exceptions by Type (over 5m)",
   "type": "table-old",
   "description": "Groups all exceptions detected in Akka.NET logs by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address,exceptiontype)(ceil(increase(akka_logs_events{cluster_role=~\"$role\",akka_address=~\"$address\",exceptiontype=~\".+\"}[5m])))"
    }
   ]
  },
  {
   "title": "Total Errors Logged (5m)",
   "type": "stat",
   "description": "Total errors logged by Akka.NET over past 5 minutes, cumulative for all roles / cluster / exception types.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(akka_logs_events{level=\"error\",cluster_role=~\"$role\",akka_address=~\"$address\"}[5m]))"
    }
   ]
  },
  { "title": "Actor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }, "repeat": "role" },
  {
   "title": "Total Akka.NET Actors",
   "type": "graph",
   "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(cluster_role,akka_address)(akka_actor_created_starts{cluster_role=~\"$role\",akka_address=~\"$address\"}) - sum by(cluster_role,akka_address)(akka_actor_stopped_stops{cluster_role=~\"$role\",akka_address=~\"$address\"})",
     "legendFormat": "Total Actors [{{cluster_role}} ({{akka_address}})]"
    }
   ]
  },
  {
   "title": "Total Actor Throughput (msg/s)",
   "type": "stat",
   "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(irate(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[1m]))"
    }
   ]
  },
  {
   "title": "Live Actors by Type (Top 10)",
   "type": "table-old",
   "description": "Top 10 actor starts / stops by type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype)(akka_actor_created_starts{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} created"
    },
    {
     "expr": "topk(10,sum by(actortype)(akka_actor_stopped_stops{cluster_role=~\"$role\",akka_address=~\"$address\"}))",
     "legendFormat": "{{actortype}} terminated"
    }
   ]
  },
  {
   "title": "Actor Crashes by Actor / Exception (Top 10)",
   "type": "table",
   "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "topk(10,sum by(actortype, exceptiontype)(rate(akka_actor_restarts_restarts[30m])))",
     "legendFormat": "{{actortype}},{{exceptiontype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Throughput by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(rate(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  },
  {
   "title": "Akka.NET Message Totals by Type  (Top 10 over 5 minutes)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(10,sum by(messagetype)(increase(akka_messages_recv_msgs{cluster_role=~\"$role\",akka_address=~\"$address\"}[5m])))",
     "legendFormat": "{{messagetype}}"
    }
   ]
  }
 ]
}
{
 "title": "Akka.NET Cluster + Phobos 2.x Message Latency Metrics (Prometheus Data Source)",
 "description": "Message-processing latency dashboard for Akka.NET Clusters using Phobos 2.0 and OpenTelemetry.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "msgtype", "label": "msgtype", "query": "label_values(messagetype)" },
   { "name": "actortype", "label": "actortype", "query": "label_values(actortype)" }
  ]
 },
 "panels": [
  {
   "title": "[$msgtype] Cumulative Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Latency Over Time [$msgtype ]",
   "type": "heatmap",
   "description": "Heatmap of milliseconds of latency by $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(akka_messages_latency_ms_bucket{messagetype=~\"$msgtype\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution [$msgtype ]",
   "type": "bargauge",
   "description": "Heatmap of milliseconds of latency by $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(akka_messages_latency_ms_bucket{messagetype=~\"$msgtype\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "[$msgtype] Latencies When Processed by [$actortype]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Latency Over Time [$actortype / $msgtype ]",
   "type": "heatmap",
   "description": "Heatmap of milliseconds of latency by $actortype / $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(akka_messages_latency_ms_bucket{messagetype=~\"$msgtype\",actortype=~\"$actortype\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Distribution [$actortype / $msgtype ]",
   "type": "bargauge",
   "description": "Heatmap of milliseconds of latency by $actortype / $msgtype",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(akka_messages_latency_ms_bucket{messagetype=~\"$msgtype\",actortype=~\"$actortype\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}
{
 "title": "dotnet-monitor Kubernetes Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": ".NET ThreadPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": ".NET Threadpool Completed Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_completed_items_count{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "completed items {{instance}}"
    }
   ]
  },
  {
   "title": ".NET Threadpool Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_thread_count{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "thread_count {{instance}}"
    }
   ]
  },
  {
   "title": ".NET Threadpool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_queue_length{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "queue_length {{instance}}"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "CPU Usage {{instance}}"
    }
   ]
  },
  { "title": "Memory and GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 0 Size {{instance}}"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 1 Size {{instance}}"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 2 Size {{instance}}"
    },
    {
     "expr": "systemruntime_loh_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "LOH Size {{instance}}"
    },
    {
     "expr": "systemruntime_poh_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "POH Size {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{app=~\"$app\",instance=~\"$instance\"}/100",
     "legendFormat": "Total Fragmentation {{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "% Time in GC {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Alloc rate {{instance}}"
    }
   ]
  },
  {
   "title": "Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gc_heap_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "GC Heap Size"
    },
    {
     "expr": "systemruntime_working_set_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Working Set"
    }
   ]
  }
 ]
}