# staging settings
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: stress-configs
data:
  # Configuration values can be set as key-value properties
  ASPNETCORE_ENVIRONMENT: Production

  # standard Akka.NET ports for all services
  StressOptions__AkkaClusterOptions__ManagementPort: "9228"
  StressOptions__AkkaClusterOptions__UseKubernetesLease: "true"

  # configure Akka.Management K8s service discovery
  StressOptions__AkkaClusterOptions__UseKubernetesDiscovery: "true"
  StressOptions__AkkaClusterOptions__KubernetesDiscoveryOptions__PodNamespace: "akkastress"
  StressOptions__AkkaClusterOptions__KubernetesDiscoveryOptions__PodLabelSelector: "akkacluster=stress"

  # configure Serilog
  StressOptions__SerilogOptions__EnableSeq: "false"
  StressOptions__SerilogOptions__SeqHost: "seq"
  StressOptions__SerilogOptions__SeqPort: "8988"

  StressOptions__DispatcherConfig: "Defaults"

  JAEGER_AGENT_HOST: "jaeger-agent"   