{
 "title": "dotnet-monitor Kubernetes Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(app)" } },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": ".NET ThreadPool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": ".NET Threadpool Completed Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_completed_items_count{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "completed items {{instance}}"
    }
   ]
  },
  {
   "title": ".NET Threadpool Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_thread_count{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "thread_count {{instance}}"
    }
   ]
  },
  {
   "title": ".NET Threadpool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "systemruntime_threadpool_queue_length{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "queue_length {{instance}}"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "CPU Usage {{instance}}"
    }
   ]
  },
  { "title": "Memory and GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 0 Size {{instance}}"
    },
    {
     "expr": "systemruntime_gen_1_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 1 Size {{instance}}"
    },
    {
     "expr": "systemruntime_gen_2_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Gen 2 Size {{instance}}"
    },
    {
     "expr": "systemruntime_loh_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "LOH Size {{instance}}"
    },
    {
     "expr": "systemruntime_poh_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "POH Size {{instance}}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{app=~\"$app\",instance=~\"$instance\"}/100",
     "legendFormat": "Total Fragmentation {{instance}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "% Time in GC {{instance}}"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Alloc rate {{instance}}"
    }
   ]
  },
  {
   "title": "Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gc_heap_size_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "GC Heap Size"
    },
    {
     "expr": "systemruntime_working_set_bytes{app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Working Set"
    }
   ]
  }
 ]
}